import { action, internalAction, internalMutation, internalQuery, mutation, query } from "./_generated/server";
import { v } from "convex/values";
import { internal } from "./_generated/api";
import * as analysis from "./lib/analysis";
import * as firecrawl from "./lib/firecrawl";
import * as sibyl from "./lib/sibyl";
import { clamp, now } from "./lib/util";

// ─────────────────────────────────────────────────────────────────────────────
// The Provo desk: listing applications → public-opinion investigation →
// verdict. Memory (Sibyl) is read at decision time: if the team behind an
// applicant previously rugged a project, the verdict must reflect it. With
// memory off, the same application is judged with no history (the
// counterfactual).
// ─────────────────────────────────────────────────────────────────────────────

const STAR_SLUG = "zenith-finance";

// ── queries ─────────────────────────────────────────────────────────────────

export const listBoard = query({
  args: {},
  handler: async (ctx) => {
    const projects = await ctx.db.query("projects").collect();
    // featured first, then most recent application
    return projects.sort((a, b) => Number(b.featured) - Number(a.featured) || b.appliedAt - a.appliedAt);
  },
});

export const getProjectBySlug = query({
  args: { slug: v.string() },
  handler: async (ctx, args) =>
    ctx.db
      .query("projects")
      .withIndex("by_slug", (q) => q.eq("slug", args.slug))
      .first(),
});

export const listAllInternal = internalQuery({
  args: {},
  handler: async (ctx) => ctx.db.query("projects").collect(),
});

export const getProjectInternal = internalQuery({
  args: { projectId: v.id("projects") },
  handler: async (ctx, args) => ctx.db.get(args.projectId),
});

// ── seed: the demo board ────────────────────────────────────────────────────

const FIXTURES: Array<{
  name: string; slug: string; tagline: string; chain: string;
  status: string; verdict?: string; verdictSummary?: string;
  sentimentScore?: number; riskTags: string[]; featured?: boolean;
  links?: { site?: string; x?: string };
  teamNote?: string; realProduct?: boolean; simulated?: boolean;
}> = [
  // ── real Base ecosystem projects: verdicts come only from real desk reviews ──
  {
    name: "Aerodrome", slug: "aerodrome", chain: "base",
    tagline: "The leading AMM and liquidity hub on Base.",
    status: "applied", riskTags: [], featured: true, realProduct: true,
    links: { site: "https://aerodrome.finance" },
  },
  {
    name: "Uniswap", slug: "uniswap", chain: "base",
    tagline: "The largest DEX protocol, live on Base.",
    status: "applied", riskTags: [], realProduct: true,
    links: { site: "https://uniswap.org" },
  },
  {
    name: "Aave", slug: "aave", chain: "base",
    tagline: "Decentralized liquidity protocol, deployed on Base.",
    status: "applied", riskTags: [], realProduct: true,
    links: { site: "https://aave.com" },
  },
  {
    name: "Moonwell", slug: "moonwell", chain: "base",
    tagline: "Lending and borrowing protocol on Base.",
    status: "applied", riskTags: [], realProduct: true,
    links: { site: "https://moonwell.fi" },
  },
  {
    name: "BaseSwap", slug: "baseswap", chain: "base",
    tagline: "Native DEX on Base.",
    status: "applied", riskTags: [], realProduct: true,
    links: { site: "https://baseswap.fi" },
  },

  // ── labeled simulations (demo constructs — the engine + memory stories) ──
  {
    name: "ZephyrSwap", slug: "zephyrswap", chain: "base",
    tagline: "SIMULATION · perps & swaps — the desk's deeply monitored project.",
    status: "listed", verdict: "approved", sentimentScore: 71,
    riskTags: [], simulated: true, links: { site: "https://zephyrswap.example" },
    teamNote: "Fictional demo project monitored by the engine.",
    verdictSummary:
      "Simulated listing: ZephyrSwap exists so the engine demo has a project to monitor deeply. Its findings and history are generated by the live pipeline.",
  },
  {
    // THE DEMO STAR — decided live. The team's prior rug exists ONLY in Sibyl.
    name: "Zenith Finance", slug: STAR_SLUG, chain: "base",
    tagline: "SIMULATION · perps trading — the rug-recall demo applicant.",
    status: "applied", riskTags: [], simulated: true,
    teamNote: "Simulated applicant; team history is a demo construct stored in Sibyl.",
  },
];

/** Idempotent seed: real applicants + labeled simulations + rug history in Sibyl. */
export const reseedBoard = action({
  args: {},
  handler: async (ctx): Promise<string> => {
    await ctx.runMutation(internal.projects.clearProjects, {});
    return await seedBoardInternal(ctx);
  },
});

export const seedBoard = action({
  args: {},
  handler: async (ctx): Promise<string> => {
    const existing = await ctx.runQuery(internal.projects.listAllInternal, {});
    if (existing.length > 0) return `already seeded (${existing.length} projects)`;
    return await seedBoardInternal(ctx);
  },
});

async function seedBoardInternal(ctx: any): Promise<string> {

    const company = (await ctx.runQuery(internal.queries.getCompanyInternal, {})) as any;
    const t = now();
    for (const f of FIXTURES) {
      await ctx.runMutation(internal.projects.insertProject, {
        name: f.name,
        slug: f.slug,
        tagline: f.tagline,
        chain: f.chain,
        teamNote: f.teamNote,
        status: f.status,
        verdict: f.verdict,
        verdictSummary: f.verdictSummary,
        sentimentScore: f.sentimentScore,
        riskTags: f.riskTags,
        featured: f.featured ?? false,
        links: f.links,
        realProduct: f.realProduct,
        simulated: f.simulated,
        appliedAt: t - Math.floor(Math.random() * 6 * 24 * 3600_000) - 3600_000,
        decidedAt: f.verdict ? t - 3600_000 : undefined,
      });
    }

    // The Zenith team's prior rug — written into Sibyl, the ONLY place it
    // exists. With memory off, the desk reviews Zenith blind.
    await sibyl.save({
      kind: "entity",
      category: "rug_history",
      name: "aurum-finance",
      body: {
        title: "Aurum Finance",
        chain: "base",
        incident: "Exit scam on 14 Jul 2026: liquidity pulled 40 minutes after launch, ~$2.1M drained.",
        team: "Same 3 signer wallets that deployed Aurum are signers on the Zenith Finance deployer contract (on-chain cross-match).",
        status: "confirmed rug",
      },
    });
    await sibyl.save({
      kind: "event",
      text: "Rug pull: Aurum Finance (Jul 2026, ~$2.1M). Deployer signer wallets reused by 'Zenith Finance' — treat any listing application from this team as prior-offense.",
      meta: { category: "rug_history", name: "aurum-finance" },
    });

    await ctx.runMutation(internal.state.logTask, {
      company: company?._id,
      type: "remember",
      status: "complete",
      label: "Board seeded: 5 real Base applicants + 2 labeled simulations · rug history in Sibyl",
      detail: "zenith-finance applied — desk review pending. The Aurum record lives only in Sibyl memory.",
    });
    return "board seeded";
  }

export const insertProject = internalMutation({
  args: {
    name: v.string(), slug: v.string(), tagline: v.string(), chain: v.string(),
    teamNote: v.optional(v.string()), status: v.string(), verdict: v.optional(v.string()),
    verdictSummary: v.optional(v.string()), sentimentScore: v.optional(v.number()),
    riskTags: v.array(v.string()), featured: v.boolean(), appliedAt: v.number(),
    decidedAt: v.optional(v.number()),
    links: v.optional(v.object({ site: v.optional(v.string()), x: v.optional(v.string()), docs: v.optional(v.string()) })),
    realProduct: v.optional(v.boolean()),
    simulated: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => ctx.db.insert("projects", args),
});

export const clearProjects = internalMutation({
  args: {},
  handler: async (ctx) => {
    const all = await ctx.db.query("projects").collect();
    for (const p of all) await ctx.db.delete(p._id);
    return all.length;
  },
});

// ── the desk review (listing investigation) ─────────────────────────────────

export const startReviewBySlug = mutation({
  args: { slug: v.string() },
  handler: async (ctx, args) => {
    const project = await ctx.db
      .query("projects")
      .withIndex("by_slug", (q) => q.eq("slug", args.slug))
      .first();
    if (!project) throw new Error(`no project ${args.slug}`);
    if (project.status !== "applied" && project.status !== "under_review") {
      throw new Error(`${project.name} already decided: ${project.status}`);
    }
    await ctx.db.patch(project._id, { status: "under_review" });
    await ctx.scheduler.runAfter(0, internal.projects.investigateApplication, {
      projectId: project._id,
    });
    return project._id;
  },
});

/** Dev/demo tool: clear a decision so the desk can review again (e.g. after
 * toggling memory — the counterfactual). */
export const reopenReview = mutation({
  args: { slug: v.string() },
  handler: async (ctx, args) => {
    const project = await ctx.db
      .query("projects")
      .withIndex("by_slug", (q) => q.eq("slug", args.slug))
      .first();
    if (!project) throw new Error(`no project ${args.slug}`);
    await ctx.db.patch(project._id, {
      status: "applied",
      verdict: undefined,
      verdictSummary: undefined,
      sentimentScore: undefined,
      riskTags: [],
      recalledMemories: undefined,
      evidence: undefined,
      decidedAt: undefined,
    });
    return project._id;
  },
});

export const investigateApplication = internalAction({
  args: { projectId: v.id("projects") },
  handler: async (ctx, args) => {
    const project = (await ctx.runQuery(internal.projects.getProjectInternal, {
      projectId: args.projectId,
    })) as any;
    if (!project) return;
    const company = (await ctx.runQuery(internal.queries.getCompanyInternal, {})) as any;

    const task = await ctx.runMutation(internal.state.logTask, {
      company: company?._id,
      type: "investigate",
      status: "running",
      label: `Desk review: ${project.name} (listing application)`,
    });

    // METER: desk review (credits.ts)
    if (company) {
      const meter = await ctx.runMutation(internal.credits.burn, {
        company: company._id,
        action: "desk_review",
        detail: project.name,
      });
      if (!meter.ok) {
        await ctx.runMutation(internal.state.completeTask, {
          taskId: task,
          detail: `desk review blocked — ${meter.reason}`,
        });
        await ctx.runMutation(internal.projects.revertToApplied, { projectId: args.projectId });
        return;
      }
    }

    try {
      // 1. REMEMBER — rug/team history from Sibyl. Load-bearing: memory off ⇒
      // the desk reviews with an empty record (the counterfactual).
      const memoryOn = company?.memoryEnabled ?? false;
      let memories: { name: string; text: string }[] = [];
      if (memoryOn) {
        try {
          const recalled = await sibyl.recall({
            query: `${project.name} ${project.tagline} ${project.teamNote ?? ""} team deployer history rug`.slice(0, 400),
            k: 5,
          });
          memories = recalled.map((m) => ({ name: m.name, text: m.text.slice(0, 600) }));
          await ctx.runMutation(internal.state.logTask, {
            company: company?._id,
            type: "remember",
            status: "complete",
            label: `Sibyl recall: ${memories.length} memories for ${project.name} review`,
            detail:
              memories.map((m) => `${m.name}: ${m.text.slice(0, 110)}`).join("\n") ||
              "no matching memories on record",
          });
        } catch (e: any) {
          await ctx.runMutation(internal.state.logTask, {
            company: company?._id,
            type: "remember",
            status: "failed",
            label: "Sibyl recall failed — reviewing with no record",
            detail: String(e.message ?? e).slice(0, 200),
          });
        }
      }

      // 2. public-opinion research (Firecrawl, gated by the web-research toggle;
      //    queries target the phenomenon, never the fictional brand)
      const fcEnabled = company?.webResearchEnabled ?? firecrawl.enabled();
      const plan = await analysis.planInvestigation({
        issue: {
          title: `Listing review: ${project.name}`,
          description: project.tagline,
        },
        question: "public opinion, team track record, contract/audit red flags",
        product: project.name,
        realProduct: project.realProduct ?? false,
      });
      const queries = fcEnabled ? plan.queries.slice(0, 2) : [];
      const hits: { title: string; url: string; description: string; markdown?: string }[] = [];
      for (const q of queries) {
        try {
          const results = await firecrawl.searchWithBackoff(q, 4);
          hits.push(...results);
        } catch {
          // single failed search must not kill the review
        }
      }

      // 3. evidence extraction (verbatim excerpts only)
      const extracted = fcEnabled
        ? await analysis.extractEvidence({
            issue: { title: `Listing review: ${project.name}`, description: project.tagline },
            question: "team track record, community sentiment, contract red flags",
            results: hits.slice(0, 10),
          }).catch(() => [])
        : [];

      // 4. VERDICT — memory is authoritative per the desk prompt
      const verdict = await analysis.assessListing({
        project: {
          name: project.name,
          tagline: project.tagline,
          chain: project.chain,
          teamNote: project.teamNote,
        },
        evidence: extracted.map((e) => ({ excerpt: e.excerpt, url: e.url, note: e.note })),
        memories,
      });

      const status =
        verdict.verdict === "approved" ? "listed" : verdict.verdict === "flagged" ? "flagged" : "rejected";

      // only surface memories that actually concern this project on the dossier
      // (recall casts a wide net; the verdict prompt sees everything, the
      // dossier shows only what's relevant to this applicant)
      const relevantMemories = memories.filter(
        (m) =>
          m.name.toLowerCase().includes(project.slug) ||
          m.text.toLowerCase().includes(project.name.toLowerCase())
      );

      await ctx.runMutation(internal.projects.decideProject, {
        projectId: args.projectId,
        status,
        verdict: verdict.verdict,
        verdictSummary: verdict.summary,
        sentimentScore: Math.round(clamp(verdict.sentimentScore, 0, 100)),
        riskTags: verdict.riskTags.slice(0, 5),
        recalledMemories: relevantMemories.map((m) => m.name),
        evidence: extracted
          .sort((a, b) => b.relevance - a.relevance)
          .slice(0, 4)
          .map((e) => ({ source: "web", url: e.url, excerpt: e.excerpt })),
      });

      // 5. REMEMBER (write-through): the verdict itself becomes desk memory
      if (memoryOn) {
        try {
          await sibyl.save({
            kind: "entity",
            category: "listing_verdict",
            name: project.slug,
            body: {
              project: project.name,
              verdict: verdict.verdict,
              summary: verdict.summary,
              riskTags: verdict.riskTags,
              decidedAtIso: new Date().toISOString(),
            },
            meta: { projectId: String(args.projectId) },
          });
          await sibyl.save({
            kind: "event",
            text: `Listing verdict ${verdict.verdict}: ${project.name}. ${verdict.summary}`,
            meta: { category: "listing_verdict", name: project.slug },
          });
        } catch {
          // write-through failure must not fail the verdict
        }
      }

      // ALERT: the listing verdict goes to the applicant-facing monitor feed
      await ctx.runAction(internal.alerts.sendAlert, {
        company: company._id,
        kind: "verdict",
        title: `${project.name} — listing verdict: ${verdict.verdict}`,
        body: verdict.summary,
        recurrence: relevantMemories.length
          ? `desk memory consulted: ${relevantMemories.map((m) => m.name).join(", ")}`
          : undefined,
      });

      await ctx.runMutation(internal.state.completeTask, {
        taskId: task,
        detail: `${verdict.verdict.toUpperCase()} · sentiment ${Math.round(verdict.sentimentScore)} · ${memories.length} memories consulted`,
      });
    } catch (e: any) {
      await ctx.runMutation(internal.state.completeTask, {
        taskId: task,
        status: "failed",
        detail: String(e.message ?? e).slice(0, 200),
      });
      await ctx.runMutation(internal.projects.revertToApplied, { projectId: args.projectId });
      throw e;
    }
  },
});

export const decideProject = internalMutation({
  args: {
    projectId: v.id("projects"),
    status: v.string(),
    verdict: v.string(),
    verdictSummary: v.string(),
    sentimentScore: v.number(),
    riskTags: v.array(v.string()),
    recalledMemories: v.array(v.string()),
    evidence: v.array(v.object({ source: v.string(), url: v.optional(v.string()), excerpt: v.string() })),
  },
  handler: async (ctx, args) => {
    const { projectId, ...rest } = args;
    await ctx.db.patch(projectId, { ...rest, decidedAt: now() });
  },
});

export const revertToApplied = internalMutation({
  args: { projectId: v.id("projects") },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.projectId, { status: "applied" });
  },
});
